### ISSUE TITLE
clagon/discord-questions-botへの移行について

### ISSUE THREAD

**Issue by Gon-1222** [Gon-1222/Discord-Bot-Form#6]
@clagon 
https://github.com/clagon/discord-questions-bot
の方へ替える？
使ってる人いないけど。

**Comment by clagon** [comment]
vercelだけでbot動かせそうだったから作ってみたけど、画像送る手段があんま使いやすく実装できそうにない。discord内だけで送れるのは便利そうだけど

**Comment by Gon-1222** [comment]
@clagon 
最近タップ回数とか考えると、UXどっちでもそんな変わらないんじゃないかとも思ったりもする。

技術系の話わからないんで、良い手段あるならと思ったけど微妙ならいいか...。

話しやすい環境にするほうが先な気もする笑

**Comment by clagon** [comment]
https://github.com/clagon/discord-anonymous-conversations.git
これならぎり機能するかな

https://user-images.githubusercontent.com/89688948/229120400-a4e1eec4-7485-4df0-aa8e-2908cda64615.mp4

**Comment by Gon-1222** [comment]
わざわざありがとうございます！

よくわからんけど、導入するかについてもお任せします🙇‍♂️

気づくの遅くてごめん
